// remote-react/src/components/Button.tsx
import React from 'react';

type ButtonProps = {
  label: string;
  onClick?: () => void;
};

function Button(props: ButtonProps) {
  return (
    <button
      {...props}
      type="button"
      className="re-text-black re-bg-primary hover:re-bg-primary-focus re-font-medium re-rounded-lg re-text-sm re-px-5 re-py-2 focus:re-outline-none">
      {props.label}
    </button>
  );
}

export default Button;

// remote-vue/src/components/Button.vue
<template>
    <button type="button"
        className="vu-text-black vu-bg-primary hover:vu-bg-primary-focus vu-font-medium vu-rounded-lg vu-text-sm vu-px-5 vu-py-2 focus:vu-outline-none">
        {{ label }}
    </button>
</template>
<script>
import { defineComponent } from "vue"
export default defineComponent({
    name: 'Button',
    props: {
        label: String
    },
    setup(props) {
        props.label = ''
    }
});
</script>
