// remote-react/src/components/Input.tsx
import React from 'react';
import { ButtonHTMLAttributes } from 'react';

type ButtonProps = ButtonHTMLAttributes<Omit<HTMLButtonElement, 'labels'>> & {
  children?: any;
};
function Input(props: ButtonProps) {
  return (
    <input
      {...props}
      type="text"
      className="re-bg-gray-50 re-border re-border-gray-300 re-text-gray-900 re-text-sm re-rounded-lg focus:re-ring-primary focus:re-border-primary re-outline-none focus:re-outline-none re-block re-w-full re-p-2.5"></input>
  );
}

export default Input;

// remote-vue/src/components/Input.vue
<template>
    <input type="text" v-model="value" :placeholder="placeholder"
        className="vu-bg-gray-50 vu-border vu-border-gray-300 vu-text-gray-900 vu-text-sm vu-rounded-lg focus:vu-ring-primary focus:vu-border-primary vu-outline-none focus:vu-outline-none vu-block vu-w-full vu-p-2.5" />
</template>
<script>
import { defineComponent } from "vue"
export default defineComponent({
    name: 'Input',
    props: {
        value: String,
        placeholder: String,
    },
    methods: {
        onChange(v) {
            this.$emit('input', v);
        }
    },
    setup(props) {
        props.value = '';
        props.placeholder = '';
    },
});
</script>
