// remote-vue/src/views/NotFound.vue
<template>
  <div class="vu-w-full vu-h-screen vu-p-4">
    <div class="vu-flex vu-flex-col vu-p-12 vu-items-center vu-justify-center">

      <div class="vu-text-5xl vu-font-bold">404</div>
      <div class="vu-text-xl">
        This page cannot be found in Vue App </div>
    </div>
  </div>
</template>
<script></script>

// shell/src/components/not-found/not-found.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'not-found-home',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.scss'],
})
export class NotFoundComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {}
}

<div class="an-w-full an-h-screen an-p-4">
  <div class="an-flex an-flex-col an-p-12 an-items-center an-justify-center">
    <div class="an-text-5xl an-font-bold">404</div>
    <div class="an-text-xl">This page cannot be found in Angular App</div>
  </div>
</div>
